// Bake the four prompt templates into public/index.html so the "The prompt"
// section is present in the raw HTML for crawlers, slow connections, and
// no-JS visitors — instead of rendering a literal "Loading".
//
// The strings are generated by the REAL builders (buildPrompt / buildLivePrompt
// over the same placeholder fixture the server uses for /api/state.prompts),
// so the "rendered from the same code" claim stays true. The client still
// overwrites these <pre> blocks with the identical live template on hydration.
//
// Re-run whenever the prompt wording changes:  node scripts/render-prompts.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildPrompt, buildLivePrompt } from '../lib/predictor.js';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const htmlPath = path.join(root, 'public', 'index.html');

// Identical placeholder fixture to server.js's promptTemplates.
const templateMatch = {
  home: { name: '{HOME TEAM}', score: '{HOME GOALS}' },
  away: { name: '{AWAY TEAM}', score: '{AWAY GOALS}' },
  stage: '{STAGE}',
  kickoff: '{KICKOFF UTC}',
  venue: '{VENUE}',
  status: { detail: '{MATCH CLOCK}' },
  keyEvents: ['{GOALS AND RED CARDS SO FAR}'],
};

const prompts = {
  'prompt-locked': buildPrompt(templateMatch),
  'prompt-locked-ko': buildPrompt({ ...templateMatch, market: 'advance' }),
  'prompt-live': buildLivePrompt(templateMatch),
  'prompt-live-ko': buildLivePrompt({ ...templateMatch, market: 'advance' }),
};

const escapeHtml = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

let html = fs.readFileSync(htmlPath, 'utf8');
let changed = 0;
for (const [id, text] of Object.entries(prompts)) {
  // Match <pre id="ID" ...>ANYTHING</pre>, replace inner content only.
  const re = new RegExp(`(<pre id="${id}"[^>]*>)([\\s\\S]*?)(</pre>)`);
  if (!re.test(html)) {
    console.error(`WARN: <pre id="${id}"> not found in index.html`);
    continue;
  }
  html = html.replace(re, `$1${escapeHtml(text)}$3`);
  changed++;
}

fs.writeFileSync(htmlPath, html);
console.log(`Baked ${changed}/4 prompt blocks into public/index.html`);
